apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: robusta
  namespace: robusta
spec:
  chart:
    spec:
      chart: robusta
      version: v0.10.x
      sourceRef:
        kind: HelmRepository
        name: robusta
        namespace: flux-system
  interval: 5m
  releaseName: robusta
  values:
    clusterName: resume-cluster
    globalConfig:
      signing_key: "{{ env.SIGNING_KEY }}"
      account_id: "{{ env.ACCOUNT_ID }}"
    sinksConfig:
    - slack_sink:
        name: main_slack_sink
        slack_channel: "{{ env.SLACK_SINK_CHANNEL_NAME}}"
        api_key: "{{ env.SLACK_SINK_API_KEY }}"
    - robusta_sink:
        name: robusta_ui_sink
        token: "{{ env.ROBUSTA_SINK_TOKEN }}"
    enablePrometheusStack: true
    enablePlatformPlaybooks: true
    runner:
      sendAdditionalTelemetry: false
      additional_env_vars:
      - name: SIGNING_KEY
        valueFrom:
          secretKeyRef:
            name: robusta-env-secrets
            key: signing_key
      - name: ACCOUNT_ID
        valueFrom:
          secretKeyRef:
            name: robusta-env-secrets
            key: account_id
      - name: SLACK_SINK_CHANNEL_NAME
        valueFrom:
          secretKeyRef:
            name: robusta-env-secrets
            key: slack_sink_channel_name
      - name: SLACK_SINK_API_KEY
        valueFrom:
          secretKeyRef:
            name: robusta-env-secrets
            key: slack_sink_api_key
      - name: ROBUSTA_SINK_TOKEN
        valueFrom:
          secretKeyRef:
            name: robusta-env-secrets
            key: robusta_sink_token
    customPlaybooks:
    - triggers:
        - on_deployment_update: {}
      actions:
        - resource_babysitter:
            omitted_fields: []
            fields_to_monitor: ["spec.template.spec.containers[0].image"]

