
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-sync.yaml
- gotk-components.yaml
- helmrepository.yaml
- image-update-automation.yaml
- sync.yaml
patchesStrategicMerge:
- patch-aws-ecr-autologin-arg.yaml
