
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-sync.yaml
- gotk-components.yaml
- helmrepository.yaml
- image-update-automation.yaml
- sync.yaml
patches:
  - patch: |
      apiVersion: image.toolkit.fluxcd.io/v1beta2
      kind: ImageRepository
      metadata:
        name: personal-resume-webapp
        namespace: flux-system
      spec:
        provider: gcp
    target:
      kind: ImageRepository
      name: personal-resume-webapp
