apiVersion: apps/v1
kind: ServiceAccount
metadata:
  name: image-reflector-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
      - args:
        - --aws-autologin-for-ecr
