---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vela-controller-sync
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./gitops/infra/vela-system/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: cert-manager-sync
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   path: ./gitops/infra/cert-manager
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app-sync
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system
      namespace: flux-system
    - name: vela-custom-definitions-sync
      namespace: flux-system
    # - name: cert-manager-sync
    #   namespace: flux-system
  interval: 10m0s
  path: ./gitops/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system