---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vela-sync
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./gitops/cluster/vela-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app-sync
  namespace: flux-system
spec:
  dependsOn:
    - name: vela-sync
      namespace: flux-system
  interval: 10m0s
  path: ./gitops/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system