apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubevela
  namespace: vela-system
spec:
  chart:
    spec:
      chart: vela-minimal
      version: "1.6.x"
      sourceRef:
        kind: HelmRepository
        name: kubevela
        namespace: flux-system
  interval: 30m
  