---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-issuers-sync
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-controller-sync
      namespace: flux-system
  interval: 10m0s
  path: ./gitops/infra/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system