---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vela-custom-definitions-sync
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./gitops/infra/vela-system/custom-definitions
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system