apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubevela
  namespace: vela-system
spec:
  chart:
    spec:
      chart: vela-core
      sourceRef:
        kind: HelmRepository
        name: kubevela
        namespace: flux-system
  interval: 5m
  