apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      version: v1.12.x
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  interval: 5m
  releaseName: external-dns
  values:
    provider: google
    sources:
    - ingress
    domainFilters:
    - sorensenstene.site
    - miljovarsel.no
    txtOwnerId: external-dns # Help tell which records are owned by external-dns.
    sync: policy # 'sync' used to make external dns clean up dns records if service/ingresses are deleted
    interval: 5m
    serviceAccount:
      create: true
      name: external-dns
      annotations:
        iam.gke.io/gcp-service-account: "external-dns-sa@personal-resume-376620.iam.gserviceaccount.com"
    nodeSelector:
      iam.gke.io/gke-metadata-server-enabled: "true"