apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    name: test
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test
  namespace: test
spec:
  components:
    - name: test
      type: frontend
      properties:
        image: gcr.io/google_containers/echoserver:1.4
        port: 8080
        hostname: sorensenstene.site