apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: personal-resume-webapp
  namespace: flux-system
spec:
  image: europe-north1-docker.pkg.dev/personal-resume-376620/personal-resume-webapp/webapp
  interval: 5m0s
  provider: gcp
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: personal-resume-webapp
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: personal-resume-webapp
  filterTags:
    pattern: '(?P<ts1>[0-9][0-9][0-9][0-9])-(?P<ts2>[0-9][0-9])-(?P<ts3>[0-9][0-9]).(?P<ts4>[0-9][0-9][0-9][0-9][0-9][0-9])'
    extract: '$ts1$ts2$ts3$ts4'
  policy:
    numerical:
      order: asc
