apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: personal-resume-webapp
  namespace: flux-system
spec:
  image: 645352605981.dkr.ecr.eu-north-1.amazonaws.com/personal-resume-webapp
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: personal-resume-webapp
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: personal-resume-webapp
  filterTags:
    pattern: '(?P<ts1>[0-9][0-9][0-9][0-9])-(?P<ts2>[0-9][0-9])-(?P<ts3>[0-9][0-9]).(?P<ts4>[0-9][0-9][0-9][0-9][0-9][0-9])'
    extract: '$ts1$ts2$ts3$ts4'
  policy:
    numerical:
      order: asc
