apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: personal-resume
  namespace: personal-resume-app
  annotations:
    app.oam.dev/publishVersion: 55220074
spec:
  components:
    - name: personal-resume
      type: frontend
      properties:
        image: 645352605981.dkr.ecr.eu-north-1.amazonaws.com/personal-resume-webapp:2023-01-17.085733 # {"$imagepolicy": "flux-system:personal-resume-webapp"}
        port: 80
        hostname: sorensenstene.site
        certificateArn: arn:aws:acm:eu-north-1:645352605981:certificate/128053c4-28af-41e2-96a9-aff248715ad7
