apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: personal-resume
  namespace: personal-resume-app
spec:
  components:
    - name: test
      type: frontend
      properties:
        image: 645352605981.dkr.ecr.eu-north-1.amazonaws.com/personal-resume-webapp:latest # {"$imagepolicy": "flux-system:personal-resume-webapp"}
        port: 80
        hostname: sorensenstene.site