apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: personal-resume
  namespace: personal-resume-app
  annotations:
    app.oam.dev/publishVersion: 12b4d4cd
spec:
  components:
    - name: personal-resume
      type: frontend
      properties:
        image: europe-north1-docker.pkg.dev/personal-resume-376620/personal-resume-webapp/webapp:2023-03-17.114159 # {"$imagepolicy": "flux-system:personal-resume-webapp"}
        port: 80
        hostname: sorensenstene.site
