apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: personal-resume
  namespace: personal-resume-app
spec:
  components:
    - name: frontend
      type: webservice
      properties:
        image: gcr.io/google_containers/echoserver:1.4
        imagePullPolicy: IfNotPresent
        exposeType: NodePort
        ports:
          - port: 8080
      traits:
          - type: gateway
            properties:
              domain: sorensenstene.site
              http:
                "/": 8080
              class: alb
              classInSpec: true